# Generated by Django 5.2.13 on 2026-04-17 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='제목')),
                ('author', models.CharField(max_length=100, verbose_name='저자')),
                ('description', models.TextField(verbose_name='설명')),
                ('author_info', models.TextField(blank=True, verbose_name='저자 정보 (AI 생성)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일시')),
            ],
            options={
                'verbose_name': '도서',
                'verbose_name_plural': '도서 목록',
                'ordering': ['-created_at'],
            },
        ),
    ]
